### PR TITLE
Update build.vars

### PR DESCRIPTION
**Pull request by TinCanTech**
Enable Windows only vars for Windows only builds.

### CODE REVIEW

**Comment by mattock** [comment]
This idea makes sense. Does this work so that if one is using windows-nsis/build-complete then the EXTRA_TARGET_CFLAGS get applied? What is the value of IMAGEROOT in that case?

**Comment by TinCanTech** [comment]
Spanner in the works -- No this does not work for windows-nsis/build-complete.
In that case IMAGEROOT is set to /{pathto}/windows-nsis/tmp/image-i686

**Comment by TinCanTech** [comment]
This works for `generic/build` and `windows-nsis/build-complete`:
```
[ $(echo $IMAGEROOT | grep 'win') ] && EXTRA_TARGET_CFLAGS="-Wl,--dynamicbase,--nxcompat"
[ $(echo $IMAGEROOT | grep 'i686') ] && EXTRA_TARGET_CFLAGS="-Wl,--dynamicbase,--nxcompat"
[ $(echo $IMAGEROOT | grep 'x86_64') ] && EXTRA_TARGET_CFLAGS="-Wl,--dynamicbase,--nxcompat"
```
Although, for some reason this does not work with `-q` ?

Any other tests I should try ?

**Comment by selvanair** [comment]
Useful to make this option conditional, but  requiring IMAGEROOT to contain a word ("win") does not appear very robust. In our case the option being added is mingw specific, so what about parse CHOST for "mingw" ? And, avoiding another subshell for grep,

case "${CHOST}" in
     *mingw*) EXTRA_TARGET_CFLAGS="-Wl,--dynamicbase,--nxcompat";;
esac

**Comment by TinCanTech** [comment]
Seems like a logical choice.  Quick tests show it works for build-complete and generic/build

Shall I submit again with @selvanair 's proposal ?

**Pull request closed without merging**
