### PR TITLE
Configs migration: add note to user

### PR DESCRIPTION
**Pull request by lstipakov**
When configs are migrated from config to config-auto, create a text file in config directory with explanation.

Remove this file on uninstall.

Signed-off-by: Lev Stipakov <lev@openvpn.net>

### CODE REVIEW

**Comment by lstipakov** [comment]
Ping @selvanair @flichtenheld

**Review by flichtenheld — APPROVED** [review]
Looks good to me

**Comment by lstipakov** [comment]
> Looks good to me

Do you have a possibility/time to actually test this feature? For example:

(assuming you have clean system)

 - Install 2.4.12 (latest 2.4 version), make sure that `OpenVPN Service` component will be installed
 - In Windows service console make sure that service status is `Running`
 - Copy any `.ovpn` profile to `C:\Program Files\OpenVPN\config`
 - Install the client with the fix from [here](https://github.com/OpenVPN/openvpn-build/actions/runs/3892328993)
 - Check that `.ovpn` profile has been moved to `C:\Program Files\OpenVPN\config-auto` and `C:\Program Files\OpenVPN\config` contains `Where are my configs files.txt` file.
 - Uninstall the client
 - Make sure that `C:\Program Files\OpenVPN\config\Where are my configs files.txt` is removed

I did all that, but would be nice for someone else to confirm.

**Review by selvanair — APPROVED** [review]
Looks good and works as expected.

**Pull request merged**
