### PR TITLE
Release Unification Project

### PR DESCRIPTION
**Pull request by flichtenheld**
This make openvpn-build the one central place for release build scripts.
Merges

- OpenVPN/openvpn-release-scripts and
- OpenVPN/sbuild_wrapper

Adds submodules for

- OpenVPN/openvpn
- OpenVPN/openvpn-gui
- microsoft/vcpkg

### CODE REVIEW

**Comment by lstipakov** [comment]
LGTM - I was able to build MSI locally. 

Let's get rid of `build-and-package-env-sample.ps1`. Instead of it, make changes to `build-and-package.ps1`

 - set `VCPKG_ROOT` to `${basedir}\src\vcpkg`
 - set `VCPKG_OVERLAY_PORTS` to `${basedir}\windows-msi\vcpkg-ports`
 - replace `-nosign` with `-sign`
 - make `ManifestCertificateThumbprint` optional
 - set `ManifestTimestampRFC3161Url` to `http://timestamp.digicert.com`

I would also make `nodevprompt` behavior default and make it caller's responsibility to run this script from VS command prompt.

**Comment by flichtenheld** [comment]
> LGTM - I was able to build MSI locally.
> 
> Let's get rid of `build-and-package-env-sample.ps1`. Instead of it, make changes to `build-and-package.ps1`
> 
>     * set `VCPKG_ROOT` to `${basedir}\src\vcpkg`
> 
>     * set `VCPKG_OVERLAY_PORTS` to `${basedir}\windows-msi\vcpkg-ports`
> 
>     * replace `-nosign` with `-sign`
> 
>     * make `ManifestCertificateThumbprint` optional
> 
>     * set `ManifestTimestampRFC3161Url` to `http://timestamp.digicert.com`
> 
> 
> I would also make `nodevprompt` behavior default and make it caller's responsibility to run this script from VS command prompt.

All done. Except I just removed nodevprompt completely. Could not get build to work without setting up the dev env before calling the script.

**Comment by lstipakov** [comment]
Looks good, I was able to build MSIs locally.

I wonder if this will break existing openvpn -> openvpn-build build automation, since openvpn-build workflow might not pick the latest openvpn master or release/2.6 commit - but instead will pick the point pointed by submodule.

**Comment by lstipakov** [comment]
OTOH if we build in clean environment (like GH), `git submodule --init` will fetch the latest commit.

**Comment by lstipakov** [comment]
Ah stupid me, that's why we have `--remote` option.

**Review by lstipakov — APPROVED** [review]

**Pull request merged**
