### PR TITLE
travis-ci config

### PR DESCRIPTION
**Pull request by chipitsine**
travis-ci allows automation of pull request build testing

### CODE REVIEW

**Comment by mattock** [comment]
This looks like a good starting point. Later we could go with build-complete, which would catch even more issues. Based on Travis-CI  that should be doable.

**Comment by chipitsine** [comment]
what is "build-complete" ?

**Comment by mattock** [comment]
See the [build documentation](https://community.openvpn.net/openvpn/wiki/BuildingUsingGenericBuildsystem#CreatingaNSISinstallerwindows-nsissubdir). That said, converting build-complete build process to Travis-CI would be way more difficult, because we'd need to install a bunch of dependencies, run custom scripts, etc. Plus my Windows "buidslave" already runs build-complete/build-snapshot against "master" and "release/2.3" branches on new commits, so I think we're fine.

**Comment by chipitsine** [comment]
if you mean creating nsis installer on travis, I think it would be overkill and not very neccessary.
currently, I think, travis will build pull request and tell us whether build is passing or not. let us stick on that thing first.

**Comment by mattock** [comment]
Yes, exactly. We're on the same page then.

**Pull request merged**
