### PR TITLE
small fixes and aarch64 support

### PR DESCRIPTION
**Pull request by ordex**
one patch is about adding support for the aarch64 (ARM64) cross-compiler and the others are fixing small glitches I found while using the build script.

### CODE REVIEW

**Comment by mattock** [comment]
So the error message is this:
```
Build openssl
target already defined - mingw (offending arg: Wl,--dynamicbase,--nxcompat)
FATAL: Configure openssl
```
The arguments it complains about are the defaults given in [generic/build.vars#44](https://github.com/OpenVPN/openvpn-build/blob/master/generic/build.vars#L44). These were introduced fairly recently in [PR#79](https://github.com/OpenVPN/openvpn-build/pull/79).

**Comment by ordex** [comment]
not sure what to do. These flags were also giving me troubles when compiling for arm64 and I had to comment them out. Will try to see if there is something I introduced that is conflicting.

**Comment by chipitsine** [comment]
as for amd64 - we should add it to travis-ci build matrix, I think
otherwise, it could get broken

**Comment by chipitsine** [comment]
we can strip offending commit for now, right ?

**Comment by ordex** [comment]
@mattock when was the last time that these tests have been executed on master?

**Comment by mattock** [comment]
It is interesting that commit [build.vars: allow EXTRA_TARGET_CFLAGS to be specified on command line](https://github.com/OpenVPN/openvpn-build/pull/100/commits/6ae9644c7246115a61f6bb20e4b89ba0eebdd77d) _seems_ to break the build, as the flags it affects have been present [since May](https://github.com/OpenVPN/openvpn-build/pull/79). Looking at commit logs it looks like [moving from OpenSSL 1.0.2k to 1.0.2l](https://github.com/OpenVPN/openvpn-build/commit/41e412912bee6faa1dee871db1a54f4fe13f4b49) might be the actual problem. But then again, I was able to build with OpenSSL 1.0.2l just fine.

@ordex: could you do what @chipitsine suggested and (temporarily) remove 6ae9644c724. If that helps, then we know a bit more.

**Comment by ordex** [comment]
quite weird because I had this problem also during my build (but I thought it was a aarch64 specific problem) thus I introduced  6ae9644 to allow me to unset those flags from command line. Anyway, I am going to push another branch without this commit and make a pull request for that.

**Comment by ordex** [comment]
This pull request won't be merged as the last commit is breaking the OpenSSL build process

**Pull request closed without merging**
