### PR TITLE
update pkcs11-helper to 1.22 from https://github.com/OpenSC/pkcs11-helper/

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by mattock** [comment]
@chipitsine is this related to the lack of OpenSSL 1.1 support in earlier pkcs11-helper versions?

**Comment by chipitsine** [comment]
kind of.

as far, as I understand pkcs11-helper has moved to github, sourceforge is very outdated.

**Comment by mattock** [comment]
I'll try to push out new Windows installers next week. They should include this PR also.

**Comment by chipitsine** [comment]
good news!

I'm afraid we currently do not have tests for pkcs11 at all.
just "ok, it builds".

we should ask people who use it, to test it.
after 1.11 --> 1.22 is stabilized, I'll update travis-ci for core openvpn. and I'll try to build openvpn-build with openssl-1.1.0

**Comment by chipitsine** [comment]
as installer is released, can we merge this ?

**Comment by mattock** [comment]
Jan on openvpn-devel mailing list [confirmed](https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg15075.html) that the upgraded pkcs11-helper works fine. Merging.

**Pull request merged**
