### PR TITLE
make build.bat exit with error code if error happens

### PR DESCRIPTION
**Pull request by chipitsine**
endlocal removed "rc" variable, so let us get rid of setlocal/endlocal

### CODE REVIEW

**Comment by mattock** [comment]
I can't claim that I understand how the changes make build.bat exit with error code on error. Care to elaborate? :smile:
 
@lstipakov have you been using the "msvc" build in openvpn-build? I don't have any easy way to test this.

**Comment by chipitsine** [comment]
after "endlocal" variable "rc" is cleared

**Comment by mattock** [comment]
Ok, I see. Do you have any clue why "setlocal ENABLEDELAYEDEXPANSION" was in there in the first place? To me it does not seem to serve any purpose.

**Comment by lstipakov** [comment]
@mattock Yes I do build with "msvc". Besides we have AppVeyor VS build https://ci.appveyor.com/project/mattock/openvpn-build/history which surprisingly fails for this PR: https://ci.appveyor.com/project/mattock/openvpn-build/builds/26134311/job/309vevf0anm98k3s

**Comment by mattock** [comment]
The build failure seems unrelated. I retriggered the build just in case.

**Comment by chipitsine** [comment]
`To me it does not seem to serve any purpose.` - neither it does for me  :)

**Comment by chipitsine** [comment]
since build.bat appears to be used widely, I have some plans related to it

1) upgrade versions (currently many software components are outdated)
2) make it find VS in more intelligent way (via registry)

...
N) add builds to "openvpn/openvpn" travis-ci repo

**Comment by chipitsine** [comment]
I have found this particular error because I tried to run build.bat on travis-ci, currently travis-ci does not have any VS preinstalled (and I expected build.bat to fail, however it did not)

**Comment by rozmansi** [comment]
> Ok, I see. Do you have any clue why "setlocal ENABLEDELAYEDEXPANSION" was in there in the first place? To me it does not seem to serve any purpose.

https://ss64.com/nt/delayedexpansion.html

**Comment by lstipakov** [comment]
I wasn't that brave to remove `ENABLEDELAYEDEXPANSION` and solved that problem in a different way (see #157):

`endlocal && set rc=%rc%`

**Comment by chipitsine** [comment]
perfect

**Pull request closed without merging**
