### PR TITLE
Update wget.js

### PR DESCRIPTION
**Pull request by crazyevent**
wget.js add optional proxy support

### CODE REVIEW

**Comment by mattock** [comment]
Based on cursory research into WinHttp.WinHttpRequest object this look correct, but I can't easily test this. How do you override the default proxy settings (i.e. no proxy)?

**Comment by crazyevent** [comment]
It seems not the best way for proxy setting，any suggestions?

**Comment by mattock** [comment]
Would configuring proxy settings outside of wget.js work? For example use a system-wide proxy.

**Comment by crazyevent** [comment]
sounds good, I will try it.

**Comment by flichtenheld** [comment]
File does not exist anymore in current version.

**Pull request closed without merging**
