### PR TITLE
windows-msi: add full Windows build and packaging script

### PR DESCRIPTION
**Pull request by mattock**
The script runs exactly the same things as Buildbot Windows workers do

Signed-off-by: Samuli Seppänen <samuli@openvpn.net>

### CODE REVIEW

**Comment by mattock** [comment]
If you want to test the build script you need to - for now - adapt the openvpn_vagrant settings in `build-and-package-env.ps1`:

```
# Used internally by build-and-package.sh
$openvpn_vagrant_owner = "mattock"
$openvpn_vagrant_branch = "dockerized_buildbot_squashed"

# Used by build scripts build-and-package.sh calls
$Env:CMAKE_TOOLCHAIN_FILE = "${basedir}\vcpkg\scripts\buildsystems\vcpkg.cmake" 
$Env:CMAKE = "C:\\Program Files\\CMake\\bin\\cmake.exe"
$Env:ManifestCertificateThumbprint = "thumbprint" 
$Env:ManifestTimestampRFC3161Url = "http://timestamp.digicert.com" 
```

Right now code signing is mandatory, but it could be made optional quite easily.

**Comment by mattock** [comment]
I pretty much massacred `windows-msi/README.rst` as it had become quite outdated.

**Comment by mattock** [comment]
I tested this on a fresh "msibuilder" and found some issues with it. I'll fix those and update the PR.

**Comment by mattock** [comment]
Fixed two issues:
* Added build-openvpn-gui.ps1 under windows-msi (allows building openvpn-gui)
* Fixed faulty URL (missing "/") that broke OpenVPN builds

This latest version now works beautifully on the "msibuilder" VM in openvpn-vagrant.

**Comment by lstipakov** [comment]
To summarize:

- update openvpn (since this folder contains ports/triplets used by vcpkg upgrade)
- upgrade vcpkg itself (call `bootstrap-vcpkg.bat`) and upgrade ports
- build openssl
- build openvpn-gui

**Comment by mattock** [comment]
@lstipakov I made the fixes you proposed and build still works. Looks good now?

**Comment by mattock** [comment]
> @lstipakov I made the fixes you proposed and build still works. Looks good now?

I briefly tried to get rid of the Invoke-Webrequests that fetch msbuld-x64.bat etc. As discussed in chat fetching those build wrappers is slightly silly. On the other hand we need them, because Powershell does not understand environment files for batch files. So, afaics there are three options:

1. Continue using Invoke-Webrequest
1. Include the msbuild-*.bat scripts in openvpn-build\windows-msi
1. Concatenate the msbuild-*.bat scripts and put that new script to openvpn-build\windows-msi. I'm not sure if this works, that is, can one run vcvarsall.bat several times with different parameters and expect to get a properly configured environment (now and in the future).

I'm in favor of either 1. or 2.

I also got rid of the explicit "rst2html.py" calls. That means that if/when we want to build 2.5-based installers we need to backport your rst2html patch to openvpn.

**Comment by lstipakov** [comment]
> afaics there are three options:
> 
> 1. Continue using Invoke-Webrequest
> 2. Include the msbuild-*.bat scripts in openvpn-build\windows-msi
> I'm in favor of either 1. or 2.

Let's do 2, I think that would be an easier-to-maintain solution.

**Comment by mattock** [comment]
Added msbuild-*.bat and sign-binaries.bat to this repo. Invoke-Webrequest is no longer used. Also removed references to settings related to Invoke-Webrequest. Smoke-tested and seems to work ok.

**Review by lstipakov — APPROVED** [review]
Tested locally, managed to build 3 MSIs.

**Comment by mattock** [comment]
Thanks for review and testing @lstipakov, much appreciated!

**Pull request merged**
