### PR TITLE
remove fixup_la, restore_la (they are not needed after lzo-2.10)

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by mattock** [comment]
I'm all for scrapping useless code and Travis seems happy. Out of curiosity: why did lzo-2.09 need those functions?

**Comment by chipitsine** [comment]
when I tried to remove that function earlier, compilation failed on lzo. So, it was really neccessary.
diff between lzo 2.09 and 2.10 is 6300+ lines.

"LZO 2.10 has been released; a small update that fixes various build issues"

I tried to remove it, compilation is not failing anymore.

**Comment by chipitsine** [comment]
any news here ?

**Comment by chipitsine** [comment]
@mattock , any news here ?

**Comment by mattock** [comment]
@chipitsine I will merge this.

**Pull request merged**
