### PR TITLE
Update build.vars

### PR DESCRIPTION
**Pull request by TinCanTech**
Enable Windows only vars for only Windows builds

### CODE REVIEW

**Comment by selvanair** [comment]
This one looks good :)

**Comment by chipitsine** [comment]
will it work on non bash ?

**Comment by selvanair** [comment]
Any reason for suspecting that? Its only a simple pattern matching in case label -- nothing bash-specific.

**Comment by TinCanTech** [comment]
I took a moment to run `build-complete` under `login:/bin/bash` and again `login:/bin/sh` on **Ubuntu 18.04** .. the results were 100% success. I am running the binary on Win10 as server right now :)

**Pull request merged**
