### PR TITLE
win: support for Visual Studio 2017

### PR DESCRIPTION
**Pull request by lstipakov**
This patch enables building openvpn with Visual Studio 2017.

VS2017 build is added to AppVeyor.

Signed-off-by: Lev Stipakov <lev@openvpn.net>

### CODE REVIEW

**Comment by lstipakov** [comment]
Note that this requires openvpn with VS2017 support (https://github.com/lstipakov/openvpn/commit/720d70a3043206fbe6dcb609c7afae6f54d97354)

AppVeyor build agains that branch:  https://ci.appveyor.com/project/lstipakov/openvpn-build/build/openvpn-build-19

**Comment by rozmansi** [comment]
ACK

I have tested this patch and can confirm it works as advertised:
```
Sun Sep 30 10:25:59 2018 OpenVPN 2.5_git Windows-MSVC [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Sep 30 2018
Sun Sep 30 10:25:59 2018 Windows version 6.2 (Windows 8 or greater) 64bit
Sun Sep 30 10:25:59 2018 library versions: OpenSSL 1.0.2p  14 Aug 2018, LZO 2.06
```

One side note, though... I am using this `build-env-local.bat`:
```
@echo off

set GITHUB_USER=lstipakov
set OPENVPN_VERSION=vs2017
set OPENVPN_BRANCH=vs2017
set OPENVPN_SOURCE=git

set OPENVPN_URL=https://github.com/%GITHUB_USER%/openvpn/archive/%OPENVPN_VERSION%.tar.gz
set OPENVPN_GIT=https://github.com/lstipakov/openvpn.git
```

And, I get an extra `download.tmp\master.tar` and `build.tmp\openvpn-master` folder containing the OpenVPN/master branch. Not a biggie, but looking at `build.bat` I fail to see a reason for this extra download.

**Comment by chipitsine** [comment]
great work :)

some thoughts (in random order)

1) does that documentation require some update https://community.openvpn.net/openvpn/wiki/BuildingUsingMsvcBuildsystem ? (people sometime use it)

2) is windows vista supported ? (vs2017 does not build for win xp, right ?)

3) windows is different in string formatting, have a look at note by Selva Nair: https://github.com/OpenVPN/openvpn-gui/pull/151#issuecomment-289246603

**Comment by chipitsine** [comment]
also, both readme files state that "msvc is not maintained"

https://github.com/OpenVPN/openvpn-build/blob/master/msvc/README
https://github.com/OpenVPN/openvpn-build/blob/master/README

**Comment by chipitsine** [comment]
another thought - App Veyor allows to store build artifacts. for the reason I have no idea why, I did not enable them in cygwin build.

shall we enable artifacts for VS builds ?

**Comment by chipitsine** [comment]
Do you mean manual check or kind of ci check?

**Comment by rozmansi** [comment]
Ouch, just realized there are 762 hits when searching for "printf" in OpenVPN source code. Mostly all contain at least one `%s`. Too many to check manually.

`_In_z_ _Printf_format_string_`: the run-time variants of `printf()` already have this in their `format` parameter declaration. Perhaps we should add it to OpenVPN specific `sprintf()` wrappers too and see what Visual Studio Code Analysis tool has to say about it.

I don't think this is really a problem: given the amount of `printfs()` in OpenVPN code issues should arise in seconds. However, the openvpn.exe compiled using Visual Studio worked fine in my test run.

**Comment by lstipakov** [comment]
I have updated READMEs (new commit) and community wiki (https://community.openvpn.net/openvpn/wiki/BuildingUsingMsvcBuildsystem).

**Comment by mattock** [comment]
Approved by two people -> merging.

**Pull request merged**
