### PR TITLE
include missing win32 libraries when using static built openssl

### PR DESCRIPTION
**Pull request by johnmah**
addresses https://github.com/OpenVPN/openvpn-build/issues/111

### CODE REVIEW

**Comment by chipitsine** [comment]
Maybe add here https://github.com/OpenVPN/openvpn-build/blob/master/generic/build.vars#L36 ?

**Comment by johnmah** [comment]
if you move adding the extra libraries required for static linking to the suggested spot, then you will need to duplicate or move the Windows build detection logic into the `build.vars` file (it's done here: https://github.com/OpenVPN/openvpn-build/blob/master/generic/build#L363).

**Comment by chipitsine** [comment]
ok, it does make sense.

however, why do you set instead OPENSSL_LIBS of LDFLAGS?

**Comment by johnmah** [comment]
LDFLAGS implies global flags across all binaries, which may not be the case. OPENSSL_LIBS implies that they are required where linking w/ OpenSSL libraries is required.

**Comment by chipitsine** [comment]
OK, makes sense

**Comment by chipitsine** [comment]
@johnmah , can you please add couple of builds to travis-ci build matrix ?

**Comment by johnmah** [comment]
@chipitsine i added the static win32/64 builds to travis-ci. that work for you?

**Comment by chipitsine** [comment]
@mattock , can you merge it please ?

**Comment by chipitsine** [comment]
@johnmah , I'm not sure we need depcache + static builds

as for me, I would get rid of depcache

**Comment by mattock** [comment]
This PR looks good afaics, so merging.

@chipitsine : I would keep depcache in there for now. I rarely use it, but when modifying openvpn.nsi it is quite useful as it cuts down compile time a lot.

**Pull request merged**
