### PR TITLE
fix for trac#806

### PR DESCRIPTION
**Pull request by chipitsine**
I will upload installers soon

### CODE REVIEW

**Comment by chipitsine** [comment]
test installer:  https://chipitsine.github.io/oem/openvpn-install-2.4.0-I601.exe

**Comment by mattock** [comment]
Based on discussion in https://community.openvpn.net/openvpn/ticket/806 this PR does the trick as long as the installer is _not_ Unicode.

@chipitsine : does it make sense to merge this now, if Unicode installers are behind the corner?

**Comment by chipitsine** [comment]
it does make sense.

I'm a bit afraid of couple of things here

- I rolled installer using nsis-2.50, should we upgrade build infrastructure to 2.50 ?
- /OEM is not default option, so it might have some side effects, I asked people to test it. maybe we should ask in openvpn-users mailing list as well ?

**Comment by chipitsine** [comment]
this issue will be addressed separately in unicode installer

**Comment by mattock** [comment]
Typically when I ask people to test installers nobody or maybe one guy responds. So, asking on openvpn-users definitely makes sense.

**Comment by chipitsine** [comment]
can you ask or should I ask myself ?

actually, I think after we will invest in automated testing, it will be more simple

**Comment by mattock** [comment]
@chipitsine : you go ahead and ask.

Improving automated testing is always good, but we can't cover all the corner-cases no matter what we do. So some of the problems will only revealed once real people start using our code in production. The Chocolatey Git snapshot repository will make it easier for these people, who are not terribly afraid of OpenVPN breaking, to stay up-to-date.

It would be really nice to create a system which generates Windows installers automatically from each pull request, and puts them to a public place for download. This would probably be a fair amount of work, but definitely doable using GitHub APIs.

**Comment by chipitsine** [comment]
by automating I mean chocolatey in first place. can you contact current chocolatey maintainer ?

as for building installer on every PR, it is 1-2 days of work. jenkins is capable of such github interoperation, I will install it soon. stay tuned.

**Comment by mattock** [comment]
@chipitsine : so Jenkins has a PR-building feature built-in?

**Comment by chipitsine** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

jenkins is often crappy, it usually requires some efforts to get it working. but generally speaking it worth that.

**Comment by mattock** [comment]
It seems that recent versions of Buildbot can also handle notifications from GitHub:

* http://docs.buildbot.net/current/manual/cfg-wwwhooks.html#chsrc-GitHub
* https://developer.github.com/v3/activity/events/types/#pullrequestevent

I'll have to upgrade the buildmaster soonish. and will look into PR building at the same time.

**Comment by selvanair** [comment]
Although OEM to ANSI may work for some languages at least for multibyte encodings it will just replace some gibberish with some other gibberish else, isn't it? I don't have a setup to test this so just guessing.  If so, I think its better to wait for the planned unicode version...

**Comment by chipitsine** [comment]
it is better to fix what can be easily fixed instead of waiting.

**Comment by chipitsine** [comment]
I tested on japanese windows.

original installer

original

patched installer (please note "nsis-2.50" on the screen)

oem

**Comment by selvanair** [comment]
Well, that looks good.

**Comment by chipitsine** [comment]
can we merge it?

nobody on list reported a problem:)

**Comment by mattock** [comment]
I think the worst case scenario is that non-english characters in NSI logs look funky for a _different_ subset of people than now. So this is not a high-risk change imho.

What if we do this:
1. We merge this PR
1. I build new 2.4.0 installer with this PR
1. I update 2.4.0 download links to point to the new installer
1. We monitor the mailing list and forums for a while for problems

If problems are found, I can trivially point the download links back to the previous, known-good installer.

**Comment by chipitsine** [comment]
I know of only russian windows to have different code pages 866 <--> 1251 for console and gui. It might happen, there's no any other language like that.

however, I tried japanese (see screenshot above), I can download from MSDN any language and give it a try.

I agree with your steps. Can you merge it and re-release 2.4.0 ?

**Comment by chipitsine** [comment]
good news, https://sourceforge.net/p/nsis/bugs/1171/
so, I expect this to work in nsis-3.02 as well

**Comment by mattock** [comment]
@selvanair : any comments?

**Comment by selvanair** [comment]
@mattock Agreed, let's merge this.

**Pull request merged**
