### PR TITLE
added /SOLID

### PR DESCRIPTION
**Pull request by chipitsine**
see http://nsis.sourceforge.net/Reference/SetCompressor for more details

### CODE REVIEW

**Comment by chipitsine** [comment]
can we merge it?

**Comment by mattock** [comment]
@chipitsine : what is the difference in size between SOLID and non-SOLID installers?

The /SOLID flag means that the installer has to be extracted fully before it can be launched. People who have huge installers apparently see very long delay (10-12 seconds) before the installer starts[[1]](http://neilmitchell.blogspot.fi/2013/11/nsis-plugins-and-lzma-solid.html)[[2]](http://forums.winamp.com/archive/index.php/t-208942.html). In our case the delay is probably reasonable (<0.5 secs).

**Comment by chipitsine** [comment]
with         SOLID:  3378698
without    SOLID:  3830845

**Comment by chipitsine** [comment]
in our case, I suspect the delay is due to windows defender (or other antivirus)

**Comment by mattock** [comment]
@chipitsine : do you have a /SOLID-enabled installer available somewhere?

**Comment by chipitsine** [comment]
http://chipitsine.github.io/solid/openvpn-install-2.4.0-I601.exe

**Comment by mattock** [comment]
The above installer displays an "Unpacking data" window for <0,5 seconds on a I5 laptop. I think that is acceptable. About ~12% is cut off the installer size. I think this is a fair compromise, so let's get this in.

**Pull request merged**
