### PR TITLE
Adapt WiX to new MSVC builds

### PR DESCRIPTION
**Pull request by mattock**

### CODE REVIEW

**Comment by mattock** [comment]
This currently fails with

```
PS C:\users\vagrant\buildbot\windows-server-2019-static-msbuild\openvpn-build\windows-msi> cscript.exe .\build.wsf msi
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

BUILD: tmp\x86\gui.wixobj
RUN: "C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe" -trace -nologo -ext WixNetFxExtension -arch "x86" -dPRODUCT_PUBLISHER="OpenVPN, Inc." -dPRODUCT_NAME="OpenVPN" -dPRODUCT_VERSION="2.5.021" -dPACKAGE_VERSION="2.5.2-I601" -dPRODUCT_TAP_WIN_NAME="TAP-Windows" -dPRODUCT_TAP_WIN_COMPONENT_ID="tap0901" -dPRODUCT_PLATFORM="x86" -dPRODUCT_CODE="{E5931AF4-2A8F-48A5-AFC8-0E8A268358A0}" -dUPGRADE_CODE="{1195A47B-A37A-4055-9D34-B7A691F7E97B}" -dCONFIG_EXTENSION="ovpn" -dPROGRAM_FILES_DIR="ProgramFilesFolder" -dOPENSSL_PLAT="" -dLZO_DLL="liblzo2-2.dll" -out "tmp\x86\gui.wixobj" "gui.wxs"
candle.exe : warning CNDL1108 : The command line switch 'trace' is deprecated.
gui.wxs

BUILD: tmp\x86\msi.wixobj
RUN: "C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe" -trace -nologo -ext WixNetFxExtension -arch "x86" -dPRODUCT_PUBLISHER="OpenVPN, Inc." -dPRODUCT_NAME="OpenVPN" -dPRODUCT_VERSION="2.5.021" -dPACKAGE_VERSION="2.5.2-I601" -dPRODUCT_TAP_WIN_NAME="TAP-Windows" -dPRODUCT_TAP_WIN_COMPONENT_ID="tap0901" -dPRODUCT_PLATFORM="x86" -dPRODUCT_CODE="{E5931AF4-2A8F-48A5-AFC8-0E8A268358A0}" -dUPGRADE_CODE="{1195A47B-A37A-4055-9D34-B7A691F7E97B}" -dCONFIG_EXTENSION="ovpn" -dPROGRAM_FILES_DIR="ProgramFilesFolder" -dOPENSSL_PLAT="" -dLZO_DLL="liblzo2-2.dll" -out "tmp\x86\msi.wixobj" "msi.wxs"
candle.exe : warning CNDL1108 : The command line switch 'trace' is deprecated.
msi.wxs

C:\users\vagrant\buildbot\windows-server-2019-static-msbuild\openvpn-build\windows-msi\build.wsf(165, 20) Microsoft JScript runtime error: Don't know how to build "COPYING".
```
Adding "-trace" or "-verbose" to candle.exe command-line does not help at all in figuring out why it is failing. The BuildPath thing seems to be a "safe filesystem path construction method" according to [Microsoft docs](https://documentation.help/MS-Office-JScript/jsFileSystemBuildPath.htm).

Any suggestions or insights would be appreciated.

**Comment by mattock** [comment]
I started converting build.wsf from scratch, this time scrapping the variables, using hardcoded paths and changing the paths one path a time. That way I can make good progress without any debugging. I'll handle the re-parameterization as the last step when everything works as expected and I know what parameters are actually needed.

The only functional change so far is that "sample.ovpn" is no longer copied over, because "sample.conf" can't be found from the OpenVPN repository anymore.

**Comment by mattock** [comment]
As discussed with @lstipakov the directory layout is assumed to be like this, all on the same level:

* openvpn (=openvpn source code + build artefacts)
* vcpkg (=dependency build artefacts, e.g. openvpn-gui.exe, openssl.exe)
* openvpn-build

So build.wsf will just grab the files from known locations. This differs from the "generic" build where the "build" script similarly copied files over, and to which original windows-msi was adapted to. With the new approach we skip one redundant file copying step.

Right now the "openvpn" directory is called "build". That naming stems from Buildbot's convention (it clones to a directory called "build"). Fixing that can happen later.

**Comment by mattock** [comment]
Everything has been refactored and MSIs get generated correctly. The one final issue is that buildArm64 variable is messed up and it prevents Arm64 builds. @lstipakov do you think we still need it? Or could we just enforce Arm64 builds and document what is required to get them going? It's basically just a few Visual Studio packages away nowadays.

**Comment by lstipakov** [comment]
Last time I checked, it worked :) Could you squash all commits into a single one?

**Comment by mattock** [comment]
Squashed as requested. Also modified sign-openvpn.bat so that it is able to sign the build artefacts that are now in different places.

**Comment by mattock** [comment]
Updated windows-msi/README.rst as well. I did not include the exact build steps for openvpn, openvpn-gui, vcpkg as I considered those somewhat out of scope of a packaging system. I think we could just point people at buildbot's master.cfg once that code has been merged to openvpn-vagrant.

**Review by lstipakov — APPROVED** [review]
Tested locally, got 3 MSIs as output. Smoke-tested x64 MSI installer.

**Pull request merged**
